Add linux nodeaffinity for operator deployment
libopenstorage/operator pull request #1216
Opened 2023-08-17 13:05 UTC by nikita-bhatia

2023-08-17 21:11 UTC, piyush-nimbalkar requested changes

2023-08-17 21:11 UTC, piyush-nimbalkar commented on deploy/olm-catalog/portworx/23.7.1/portworx-certified.clusterserviceversion.yaml
> +                      - key: kubernetes.io/os
This is pod anti affinity. We need to add this in node affinity.

2023-08-18 03:58 UTC, nikita-bhatia commented
> 1. PWX-33085

Added here : https://github.com/portworx/px-installer/pull/1851

2023-08-18 04:26 UTC, piyush-nimbalkar approved these changes

2023-08-18 04:59 UTC, merged